-- SPDX-License-Identifier: AGPL-3.0-only
--
-- BGS session tokens for session restore.
-- Generated by GenerateSSOToken, consumed by RestoreSession.

CREATE TABLE bgs_sessions (
    sso_id BYTEA PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    battle_tag TEXT NOT NULL DEFAULT '',
    game_accounts JSONB NOT NULL DEFAULT '[]',
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bgs_sessions_account ON bgs_sessions (account_id);
