-- SPDX-License-Identifier: AGPL-3.0-only

-- Country catalog — static reference data for account management APIs.
-- All data from real Battle.net API captures (account.battle.net HAR, 2026-08-01).

CREATE TABLE IF NOT EXISTS countries (
    id          INTEGER PRIMARY KEY,
    alpha3      CHAR(3)  NOT NULL,
    name        TEXT     NOT NULL
);

-- Age of adulthood per country (all 244 countries default to 18).
CREATE TABLE IF NOT EXISTS country_adulthood (
    country_id      INTEGER PRIMARY KEY REFERENCES countries (id),
    adulthood_age   INTEGER NOT NULL DEFAULT 18
);

-- 244 countries from the live Battle.net API.
INSERT INTO countries (id, alpha3, name) VALUES
    (4, 'AFG', 'Afghanistan'),
    (8, 'ALB', 'Albania'),
    (12, 'DZA', 'Algeria'),
    (16, 'ASM', 'American Samoa'),
    (20, 'AND', 'Andorra'),
    (24, 'AGO', 'Angola'),
    (660, 'AIA', 'Anguilla'),
    (10, 'ATA', 'Antarctica'),
    (28, 'ATG', 'Antigua And Barbuda'),
    (32, 'ARG', 'Argentina'),
    (51, 'ARM', 'Armenia'),
    (533, 'ABW', 'Aruba'),
    (36, 'AUS', 'Australia'),
    (40, 'AUT', 'Austria'),
    (31, 'AZE', 'Azerbaijan'),
    (44, 'BHS', 'Bahamas'),
    (48, 'BHR', 'Bahrain'),
    (50, 'BGD', 'Bangladesh'),
    (52, 'BRB', 'Barbados'),
    (112, 'BLR', 'Belarus'),
    (56, 'BEL', 'Belgium'),
    (84, 'BLZ', 'Belize'),
    (204, 'BEN', 'Benin'),
    (60, 'BMU', 'Bermuda'),
    (64, 'BTN', 'Bhutan'),
    (68, 'BOL', 'Bolivia'),
    (70, 'BIH', 'Bosnia And Herzegowina'),
    (72, 'BWA', 'Botswana'),
    (74, 'BVT', 'Bouvet Island'),
    (76, 'BRA', 'Brazil'),
    (86, 'IOT', 'British Indian Ocean Territory'),
    (96, 'BRN', 'Brunei Darussalam'),
    (100, 'BGR', 'Bulgaria'),
    (854, 'BFA', 'Burkina Faso'),
    (108, 'BDI', 'Burundi'),
    (116, 'KHM', 'Cambodia'),
    (120, 'CMR', 'Cameroon'),
    (124, 'CAN', 'Canada'),
    (132, 'CPV', 'Cape Verde'),
    (136, 'CYM', 'Cayman Islands'),
    (140, 'CAF', 'Central African Republic'),
    (148, 'TCD', 'Chad'),
    (152, 'CHL', 'Chile'),
    (156, 'CHN', 'China'),
    (162, 'CXR', 'Christmas Island'),
    (166, 'CCK', 'Cocos (Keeling) Islands'),
    (170, 'COL', 'Colombia'),
    (174, 'COM', 'Comoros'),
    (178, 'COG', 'Congo'),
    (180, 'COD', 'Congo, Democratic Republic Of The'),
    (184, 'COK', 'Cook Islands'),
    (188, 'CRI', 'Costa Rica'),
    (384, 'CIV', 'Cote D''Ivoire'),
    (191, 'HRV', 'Croatia (Local Name: Hrvatska)'),
    (192, 'CUB', 'Cuba'),
    (196, 'CYP', 'Cyprus'),
    (203, 'CZE', 'Czech Republic'),
    (208, 'DNK', 'Denmark'),
    (262, 'DJI', 'Djibouti'),
    (212, 'DMA', 'Dominica'),
    (214, 'DOM', 'Dominican Republic'),
    (626, 'TLS', 'East Timor'),
    (218, 'ECU', 'Ecuador'),
    (818, 'EGY', 'Egypt'),
    (222, 'SLV', 'El Salvador'),
    (226, 'GNQ', 'Equatorial Guinea'),
    (232, 'ERI', 'Eritrea'),
    (233, 'EST', 'Estonia'),
    (231, 'ETH', 'Ethiopia'),
    (238, 'FLK', 'Falkland Islands (Malvinas)'),
    (234, 'FRO', 'Faroe Islands'),
    (242, 'FJI', 'Fiji'),
    (246, 'FIN', 'Finland'),
    (250, 'FRA', 'France'),
    (254, 'GUF', 'French Guiana'),
    (258, 'PYF', 'French Polynesia'),
    (260, 'ATF', 'French Southern Territories'),
    (266, 'GAB', 'Gabon'),
    (270, 'GMB', 'Gambia'),
    (268, 'GEO', 'Georgia'),
    (276, 'DEU', 'Germany'),
    (288, 'GHA', 'Ghana'),
    (292, 'GIB', 'Gibraltar'),
    (300, 'GRC', 'Greece'),
    (304, 'GRL', 'Greenland'),
    (308, 'GRD', 'Grenada'),
    (312, 'GLP', 'Guadeloupe'),
    (316, 'GUM', 'Guam'),
    (320, 'GTM', 'Guatemala'),
    (831, 'GGY', 'Guernsey'),
    (324, 'GIN', 'Guinea'),
    (624, 'GNB', 'Guinea-Bissau'),
    (328, 'GUY', 'Guyana'),
    (332, 'HTI', 'Haiti'),
    (334, 'HMD', 'Heard and McDonald Islands'),
    (340, 'HND', 'Honduras'),
    (344, 'HKG', 'Hong Kong'),
    (348, 'HUN', 'Hungary'),
    (352, 'ISL', 'Iceland'),
    (356, 'IND', 'India'),
    (360, 'IDN', 'Indonesia'),
    (364, 'IRN', 'Iran (Islamic Republic Of)'),
    (368, 'IRQ', 'Iraq'),
    (372, 'IRL', 'Ireland'),
    (833, 'IMN', 'Isle Of Man'),
    (376, 'ISR', 'Israel'),
    (380, 'ITA', 'Italy'),
    (388, 'JAM', 'Jamaica'),
    (392, 'JPN', 'Japan'),
    (832, 'JEY', 'Jersey'),
    (400, 'JOR', 'Jordan'),
    (398, 'KAZ', 'Kazakhstan'),
    (404, 'KEN', 'Kenya'),
    (296, 'KIR', 'Kiribati'),
    (410, 'KOR', 'Korea, South'),
    (414, 'KWT', 'Kuwait'),
    (417, 'KGZ', 'Kyrgyzstan'),
    (418, 'LAO', 'Lao People''s Democratic Republic'),
    (428, 'LVA', 'Latvia'),
    (422, 'LBN', 'Lebanon'),
    (426, 'LSO', 'Lesotho'),
    (430, 'LBR', 'Liberia'),
    (434, 'LBY', 'Libyan Arab Jamahiriya'),
    (438, 'LIE', 'Liechtenstein'),
    (440, 'LTU', 'Lithuania'),
    (442, 'LUX', 'Luxembourg'),
    (446, 'MAC', 'Macau'),
    (807, 'MKD', 'Macedonia, The Former Yugoslav Republic Of'),
    (450, 'MDG', 'Madagascar'),
    (454, 'MWI', 'Malawi'),
    (458, 'MYS', 'Malaysia'),
    (462, 'MDV', 'Maldives'),
    (466, 'MLI', 'Mali'),
    (470, 'MLT', 'Malta'),
    (584, 'MHL', 'Marshall Islands'),
    (474, 'MTQ', 'Martinique'),
    (478, 'MRT', 'Mauritania'),
    (480, 'MUS', 'Mauritius'),
    (175, 'MYT', 'Mayotte'),
    (484, 'MEX', 'Mexico'),
    (583, 'FSM', 'Micronesia, Federated States Of'),
    (498, 'MDA', 'Moldova, Republic Of'),
    (492, 'MCO', 'Monaco'),
    (496, 'MNG', 'Mongolia'),
    (499, 'MNE', 'Montenegro'),
    (500, 'MSR', 'Montserrat'),
    (504, 'MAR', 'Morocco'),
    (508, 'MOZ', 'Mozambique'),
    (104, 'MMR', 'Myanmar'),
    (516, 'NAM', 'Namibia'),
    (520, 'NRU', 'Nauru'),
    (524, 'NPL', 'Nepal'),
    (528, 'NLD', 'Netherlands'),
    (530, 'ANT', 'Netherlands Antilles'),
    (540, 'NCL', 'New Caledonia'),
    (554, 'NZL', 'New Zealand'),
    (558, 'NIC', 'Nicaragua'),
    (562, 'NER', 'Niger'),
    (566, 'NGA', 'Nigeria'),
    (570, 'NIU', 'Niue'),
    (574, 'NFK', 'Norfolk Island'),
    (580, 'MNP', 'Northern Mariana Islands'),
    (578, 'NOR', 'Norway'),
    (512, 'OMN', 'Oman'),
    (586, 'PAK', 'Pakistan'),
    (585, 'PLW', 'Palau'),
    (275, 'PSE', 'Palestinian Territory, Occupied'),
    (591, 'PAN', 'Panama'),
    (598, 'PNG', 'Papua New Guinea'),
    (600, 'PRY', 'Paraguay'),
    (604, 'PER', 'Peru'),
    (608, 'PHL', 'Philippines'),
    (612, 'PCN', 'Pitcairn'),
    (616, 'POL', 'Poland'),
    (620, 'PRT', 'Portugal'),
    (630, 'PRI', 'Puerto Rico'),
    (634, 'QAT', 'Qatar'),
    (638, 'REU', 'Reunion'),
    (642, 'ROU', 'Romania'),
    (643, 'RUS', 'Russian Federation'),
    (646, 'RWA', 'Rwanda'),
    (652, 'BLM', 'Saint Barthélemy'),
    (659, 'KNA', 'Saint Kitts And Nevis'),
    (662, 'LCA', 'Saint Lucia'),
    (663, 'MAF', 'Saint Martin (French Part)'),
    (670, 'VCT', 'Saint Vincent And The Grenadines'),
    (882, 'WSM', 'Samoa'),
    (674, 'SMR', 'San Marino'),
    (678, 'STP', 'Sao Tome And Principe'),
    (682, 'SAU', 'Saudi Arabia'),
    (686, 'SEN', 'Senegal'),
    (688, 'SRB', 'Serbia'),
    (690, 'SYC', 'Seychelles'),
    (694, 'SLE', 'Sierra Leone'),
    (702, 'SGP', 'Singapore'),
    (703, 'SVK', 'Slovakia (Slovak Republic)'),
    (705, 'SVN', 'Slovenia'),
    (90, 'SLB', 'Solomon Islands'),
    (706, 'SOM', 'Somalia'),
    (710, 'ZAF', 'South Africa'),
    (239, 'SGS', 'South Georgia And The South Sandwich Islands'),
    (724, 'ESP', 'Spain'),
    (144, 'LKA', 'Sri Lanka'),
    (654, 'SHN', 'St. Helena'),
    (666, 'SPM', 'St. Pierre And Miquelon'),
    (736, 'SDN', 'Sudan'),
    (740, 'SUR', 'Suriname'),
    (744, 'SJM', 'Svalbard And Jan Mayen Islands'),
    (748, 'SWZ', 'Swaziland'),
    (752, 'SWE', 'Sweden'),
    (756, 'CHE', 'Switzerland'),
    (158, 'TWN', 'Taiwan'),
    (762, 'TJK', 'Tajikistan'),
    (834, 'TZA', 'Tanzania, United Republic Of'),
    (764, 'THA', 'Thailand'),
    (768, 'TGO', 'Togo'),
    (772, 'TKL', 'Tokelau'),
    (776, 'TON', 'Tonga'),
    (780, 'TTO', 'Trinidad And Tobago'),
    (788, 'TUN', 'Tunisia'),
    (792, 'TUR', 'Turkey'),
    (795, 'TKM', 'Turkmenistan'),
    (796, 'TCA', 'Turks And Caicos Islands'),
    (798, 'TUV', 'Tuvalu'),
    (800, 'UGA', 'Uganda'),
    (804, 'UKR', 'Ukraine'),
    (784, 'ARE', 'United Arab Emirates'),
    (826, 'GBR', 'United Kingdom'),
    (221, 'USA', 'United States'),
    (581, 'UMI', 'United States Minor Outlying Islands'),
    (858, 'URY', 'Uruguay'),
    (860, 'UZB', 'Uzbekistan'),
    (548, 'VUT', 'Vanuatu'),
    (336, 'VAT', 'Vatican City State'),
    (862, 'VEN', 'Venezuela'),
    (704, 'VNM', 'Vietnam'),
    (92, 'VGB', 'Virgin Islands (British)'),
    (850, 'VIR', 'Virgin Islands (U.S.)'),
    (876, 'WLF', 'Wallis And Futuna Islands'),
    (732, 'ESH', 'Western Sahara'),
    (887, 'YEM', 'Yemen'),
    (894, 'ZMB', 'Zambia'),
    (716, 'ZWE', 'Zimbabwe'),
    (248, 'ALA', 'Åland Islands')
ON CONFLICT (id) DO NOTHING;

-- Seed adulthood ages (all 18, matching the live API).
INSERT INTO country_adulthood (country_id, adulthood_age)
SELECT id, 18 FROM countries
ON CONFLICT (country_id) DO NOTHING;
